const calcData = {
  buttons: [
    // modes
    {
      type: "mode",
      name: "standard",
      label: "standard &#x1f5a9",
      value: "standard",
      cssClass: "btn btn-mode btn-mode-standard",
    },
    {
      type: "mode",
      name: "scientific",
      label: "scientific &#x1f9ea",
      value: "scientific",
      cssClass: "btn btn-mode btn-mode-scientific",
    },
    // trigonometry
    {
      type: "trigonometry",
      name: "sin",
      label: "sin",
      value: null,
      cssClass: "btn btn-mode btn-sin",
    },
    {
      type: "trigonometry",
      name: "arcsin",
      label: "arcsin",
      value: null,
      cssClass: "btn btn-mode btn-arcsin",
    },
    {
      type: "trigonometry",
      name: "sin-n",
      label: "sin<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-sin-n",
    },
    {
      type: "trigonometry",
      name: "sinh",
      label: "sin<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-sinh",
    },
    {
      type: "trigonometry",
      name: "cos",
      label: "cos",
      value: null,
      cssClass: "btn btn-mode btn-cos",
    },
    {
      type: "trigonometry",
      name: "arccos",
      label: "arccos",
      value: null,
      cssClass: "btn btn-mode btn-arccos",
    },
    {
      type: "trigonometry",
      name: "cos-n",
      label: "cos<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-cos-n",
    },
    {
      type: "trigonometry",
      name: "cosh",
      label: "cos<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-cosh",
    },
    {
      type: "trigonometry",
      name: "tan",
      label: "tan",
      value: null,
      cssClass: "btn btn-mode btn-tan",
    },
    {
      type: "trigonometry",
      name: "arctan",
      label: "arctan",
      value: null,
      cssClass: "btn btn-mode btn-arctan",
    },
    {
      type: "trigonometry",
      name: "tan-n",
      label: "tan<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-sin-n",
    },
    {
      type: "trigonometry",
      name: "tanh",
      label: "tan<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-tanh",
    },
    {
      type: "trigonometry",
      name: "cot",
      label: "cot",
      value: null,
      cssClass: "btn btn-mode btn-cot",
    },
    {
      type: "trigonometry",
      name: "arccot",
      label: "arccot",
      value: null,
      cssClass: "btn btn-mode btn-arccot",
    },
    {
      type: "trigonometry",
      name: "cot-n",
      label: "cot<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-cot-n",
    },
    {
      type: "trigonometry",
      name: "coth",
      label: "cot<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-coth",
    },
    {
      type: "trigonometry",
      name: "sec",
      label: "sec",
      value: null,
      cssClass: "btn btn-mode btn-sec",
    },
    {
      type: "trigonometry",
      name: "arcsec",
      label: "arcsec",
      value: null,
      cssClass: "btn btn-mode btn-arcsec",
    },
    {
      type: "trigonometry",
      name: "sec-n",
      label: "sec<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-sec-n",
    },
    {
      type: "trigonometry",
      name: "sech",
      label: "sec<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-sech",
    },
    {
      type: "trigonometry",
      name: "csc",
      label: "csc",
      value: null,
      cssClass: "btn btn-mode btn-csc",
    },
    {
      type: "trigonometry",
      name: "arccsc",
      label: "arccsc",
      value: null,
      cssClass: "btn btn-mode btn-arccsc",
    },
    {
      type: "trigonometry",
      name: "csc-n",
      label: "csc<sup><var>n</var></sup>",
      value: null,
      cssClass: "btn btn-mode btn-csc-n",
    },
    {
      type: "trigonometry",
      name: "csch",
      label: "csc<var>h</var>",
      value: null,
      cssClass: "btn btn-mode btn-csch",
    },
    // digits
    {
      type: "digit",
      name: "digit-0",
      label: "0",
      value: 0,
      cssClass: "btn btn-num btn-0",
    },
    {
      type: "digit",
      name: "digit-1",
      label: "1",
      value: 1,
      cssClass: "btn btn-num btn-1",
    },
    {
      type: "digit",
      name: "digit-2",
      label: "2",
      value: 2,
      cssClass: "btn btn-num btn-2",
    },
    {
      type: "digit",
      name: "digit-3",
      label: "3",
      value: 3,
      cssClass: "btn btn-num btn-3",
    },
    {
      type: "digit",
      name: "digit-4",
      label: "4",
      value: 4,
      cssClass: "btn btn-num btn-4",
    },
    {
      type: "digit",
      name: "digit-5",
      label: "5",
      value: 5,
      cssClass: "btn btn-num btn-5",
    },
    {
      type: "digit",
      name: "digit-6",
      label: "6",
      value: 6,
      cssClass: "btn btn-num btn-6",
    },
    {
      type: "digit",
      name: "digit-7",
      label: "7",
      value: 7,
      cssClass: "btn btn-num btn-7",
    },
    {
      type: "digit",
      name: "digit-8",
      label: "8",
      value: 8,
      cssClass: "btn btn-num btn-8",
    },
    {
      type: "digit",
      name: "digit-9",
      label: "9",
      value: 9,
      cssClass: "btn btn-num btn-9",
    },
    // operators
    {
      type: "operator",
      name: "plus",
      label: "+",
      value: "+",
      cssClass: "btn btn-operator btn-plus",
    },
    {
      type: "operator",
      name: "minus",
      label: "-",
      value: "-",
      cssClass: "btn btn-operator btn-minus",
    },
    {
      type: "operator",
      name: "multiplication",
      label: "\xD7",
      value: "*",
      cssClass: "btn btn-operator btn-multiplication",
    },
    {
      type: "operator",
      name: "divide",
      label: "\xF7",
      value: "/",
      cssClass: "btn btn-operator btn-division",
    },
    {
      type: "operator",
      name: "equals",
      label: "=",
      value: "=",
      cssClass: "btn btn-operator btn-equal",
    },
    // signs
    {
      type: "sign",
      name: "coma",
      label: ".",
      value: ".",
      cssClass: "btn btn-sign btn-coma",
    },
    {
      type: "sign",
      name: "plus-minus",
      label: "\xB1",
      value: null,
      cssClass: "btn btn-sign btn-plus-minus",
    },
    {
      type: "sign",
      name: "parenthesis-left",
      label: "(",
      value: "(",
      cssClass: "btn btn-sign btn-parenthesis-left",
    },
    {
      type: "sign",
      name: "parenthesis-right",
      label: ")",
      value: ")",
      cssClass: "btn btn-sign btn-parenthesis-right",
    },
    // functional buttons
    {
      type: "functional",
      name: "btn-pow-2",
      label: "x\u00B2",
      value: null,
      cssClass: "btn btn-fn btn-x-pow-2",
    },
    {
      type: "functional",
      name: "btn-pow-3",
      label: "x\u00B3",
      value: null,
      cssClass: "btn btn-fn btn-x-pow-3",
    },
    {
      type: "functional",
      name: "sqrt",
      label: "\u221A",
      value: null,
      cssClass: "btn btn-fn btn-sqrt",
    },
    {
      type: "functional",
      name: "cube-root",
      label: "\u221B",
      value: null,
      cssClass: "btn btn-fn btn-cube-root",
    },
    {
      type: "functional",
      name: "y-root-of-x",
      label: "<sup>y</sup>\u221Ax",
      value: null,
      cssClass: "btn btn-fn btn-y-root-of-x",
    },
    {
      type: "functional",
      name: "ln",
      label: "ln",
      value: null,
      cssClass: "btn btn-fn btn-ln",
    },
    {
      type: "functional",
      name: "log",
      label: "log",
      value: null,
      cssClass: "btn btn-fn btn-log",
    },
    {
      type: "functional",
      name: "log-base-y-of-x",
      label: "log<sub>y</sub><var>x</var>",
      value: null,
      cssClass: "btn btn-fn btn-log-base-y-of-x",
    },
    {
      type: "functional",
      name: "e-pow-x",
      label: "e<sup>x</sup>",
      value: null,
      cssClass: "btn btn-fn btn-e-pow-x",
    },
    {
      type: "functional",
      name: "10-pow-x",
      label: "10<sup>x</sup>",
      value: null,
      cssClass: "btn btn-fn btn-10-pow-x",
    },
    {
      type: "functional",
      name: "2-pow-x",
      label: "2<sup>x</sup>",
      value: null,
      cssClass: "btn btn-fn btn-2-pow-x",
    },
    {
      type: "functional",
      name: "x-pow-y",
      label: "x<sup>y</sup>",
      value: null,
      cssClass: "btn btn-fn btn-x-pow-y",
    },
    {
      type: "functional",
      name: "factorial",
      label: "<var>n!</var>",
      value: null,
      cssClass: "btn btn-fn btn-factorial",
    },
    {
      type: "functional",
      name: "exp",
      label: "exp",
      value: null,
      cssClass: "btn btn-fn btn-exp",
    },
    {
      type: "functional",
      name: "mod",
      label: "mod",
      value: null,
      cssClass: "btn btn-fn btn-mod",
    },
    {
      type: "functional",
      name: "reciprocal",
      label: "1/x",
      value: null,
      cssClass: "btn btn-fn btn-reciprocal",
    },
    {
      type: "functional",
      name: "percentage",
      label: "%",
      value: null,
      cssClass: "btn btn-fn btn-percentage",
    },
    {
      type: "functional",
      name: "abs",
      label: "|<var>x</var>|",
      value: null,
      cssClass: "btn btn-fn btn-abs",
    },
    {
      type: "functional",
      name: "ac",
      label: "AC",
      value: null,
      cssClass: "btn btn-fn btn-ac",
    },
    {
      type: "functional",
      name: "delete",
      label: "&#x2190;",
      value: null,
      cssClass: "btn btn-fn btn-delete",
    },
    // constants
    {
      type: "constant",
      name: "e",
      label: "<var>e</var>",
      value: null,
      cssClass: "btn btn-fn btn-e",
    },
    {
      type: "constant",
      name: "pi",
      label: "<var>&#x3C0</var>",
      value: null,
      cssClass: "btn btn-fn btn-pi",
    },
  ],
};
